### PR TITLE
Moves test classes and resources into test folder.

### PR DESCRIPTION
**Pull request by markdouglasswork**
Hey Jean, let me know what you think of this. I cleaned everything not directly related to our dsl into the test folder. The app can't be started with bootRun any longer, but other than that everything works fine.

I extracted that metadata url into a property, with a few options of how to set it onesself, which I added to the readme.

### CODE REVIEW

**Comment by markdouglasswork** [comment]
I see that it's failing CI. However, since this seems to ultimately be meant as a library, it may make more sense to just build as a standard jar, rather than with assemble.

**Comment by jeanbza** [comment]
@markthemarkest Couple of ideas:
1. Terseness for the README - how about something just like 'Update `application-test.yml` appropriately' and leave it at that
2. Build failure seems legit. I think it's because of the spring-boot plugins we have in there. I'd play around with the `build.gradle` and remove all the `bootRun` stuff until it's just spring-security and whatever other minimal stuff we need. Then assemble will prob work

**Comment by markdouglasswork** [comment]
I see what you mean on #2, I'm working on that one!

**Comment by markdouglasswork** [comment]
@jadekler Let me know what you think of the latest, I think it might be good to merge in.

**Comment by jeanbza** [comment]
LGTM 👍

**Pull request merged**
